petclinicblue:
  image: w3blogfr/mypetclinic
  ports:
    - "10001:8080"
petclinicgreen:
  image: w3blogfr/mypetclinic
  ports:
    - "10002:8080"
nginx:
  image: nginx:1.9.10
  ports:
    - "81:80"
  volumes:
    - ./my-nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - petclinicblue:petclinicblue
    - petclinicgreen:petclinicgreen
